// import { Moment } from "moment";

/**
 * challenge type
 */
export type challenge = {
  character?: string | undefined;
  setting?: string | undefined;
  weekStartDt?: Date | undefined;
  weekEndDt?: Date | undefined;
};

/**
 * list if possible settings
 */
export const settings: { [key: string]: string } = {
  0: "{character} goes to the zoo",
  1: "{character} goes to a concert",
  10: "{character} writes a love letter",
  100: "{character} playing Solitaire",
  101: "{character} playing four square",
  102: "{character} playing dodge ball",
  103: "{character} doing the laundry",
  104: "{character} decorating a room",
  105: "{character} gets a care package from someone",
  106: "{character} baking a cake",
  107: "{character} looking through old family photos",
  108: "{character} puts together a time capsule",
  109: "{character} babysitting someone",
  11: "{character} throws a party",
  110: "{character} trying to get the perfect Instagram picture",
  111: "{character} goes grocery shopping",
  112: "{character} at a pet store",
  113: "{character} watching netflix",
  114: "{character} playing video games",
  115: "{character} goes to a kick boxing class",
  116: "{character} sends a post card to someone",
  117: "{character} playing Twister",
  118: "{character} goes bowling",
  119: "{character} has dessert",
  12: "{character} goes to a sporting event",
  120: "{character} plays with Play Doh",
  121: "{character} makes slime",
  122: "{character} throws a party",
  123: "{character} playing a game of mini-golf",
  124: "{character} goes on a bike ride",
  125: "{character} remodels a bathroom",
  126: "{character} hanging out on the rooftop",
  127: "{character} has a sleepover",
  128: "{character} goes to the Emergency Room",
  129: "{character} goes paint balling",
  13: "{character} playing a sport",
  130: "{character} goes wine tasting",
  131: "{character} does sit ups",
  132: "{character} goes Christmas shopping",
  133: "{character} steals something",
  134: "{character} borrows something without permission",
  135: "{character} hosts a family dinner",
  136: "{character} building a model airplane",
  137: "{character} goes to a rodeo",
  138: "{character} goes to a carnival",
  139: "{character} asks someone out on a date",
  14: "{character} doing lawn work",
  140: "{character} celebrating a birthday",
  141: "{character} goes to therapy",
  142: "{character} goes out to coffee",
  143: "{character} plays poker",
  144: "{character} runs out on a restaurant bill",
  145: "{character} catches someone shoplifting something",
  146: "{character} makes tacos",
  147: "{character} gets stranded in a small town",
  148: "{character} has a tea party",
  149: "{character} tries to impress someone",
  15: "{character} is making Christmas cookies",
  150: "{character} singing karaoke",
  151: "{character} participates in a roller derby",
  152: "{character} builds a treehouse",
  153: "{character} goes to a roller derby",
  154: "{character} builds a snowman",
  155: "{character} builds a snow fort",
  156: "{character} attends a holiday party",
  157: "{character} attends a work party",
  158: "{character} show up to a party wearing the same outfit as someone else",
  159: "{character} writes a love letter",
  16: "{character} wins a carnival prize",
  160: "{character} gets driving lessons",
  161: "{character} rakes leaves",
  162: "{character} shovels snow",
  163: "{character} sets a small fire",
  164: "{character} goes house hunting",
  165: "{character} goes ghost hunting",
  166: "{character} makes a candy necklace",
  167: "{character} crashes a party",
  168: "{character} puts eyedrops in",
  169: "{character} puts contacts in",
  17: "{character} gets stuck on a ferris wheel",
  170: "{character} tries to win something at an auction",
  171: "{character} bakes a cake",
  172: "{character} throws a surprise party",
  173: "{character} on a trampoline",
  174: "{character} runs errands",
  175: "{character} meditating",
  176: "{character} goes to a parade",
  177: "{character} is in a parade",
  178: "{character} goes sledding",
  179: "{character} goes skateboarding",
  18: "{character} dancing",
  180: "{character} running through the sprinklers",
  181: "{character} exercises",
  182: "{character} does origami",
  183: "{character} flies a kite",
  184: "{character} goes swimming",
  185: "{character} preps for a job interview",
  186: "{character} studies for a test",
  187: "{character} has a crush on someone",
  188: "{character} looks for a job",
  189: "{character} goes car shopping",
  19: "{character} cooking lunch",
  190: "{character} on a roller coaster",
  191: "{character} playing with sidwalk chalk",
  192: "{character} gets a puppy",
  193: "{character} adopts a pet",
  194: "{character} playing in the snow",
  195: "{character} playing in the rain",
  196: "{character} playing on a playground",
  197: "{character} at an arcade",
  198: "{character} takes a nap together",
  199: "{character} gets stranded in the middle of a lake",
  2: "{character} eating dinner",
  20: "{character} makes breakfast in bed for someone",
  200: "{character} gets lost in a new town",
  201: "{character} gets ready for an important meeting",
  202: "{character} gets ready for a date",
  203: "{character} goes on a late night shopping trip",
  204: "{character} wraps gifts",
  205: "{character} at a petting zoo",
  206: "{character} doing homework",
  207: "{character} at a furniture store",
  208: "{character} goes to triva night",
  209: "{character} tries to convince someone that aliens are real",
  21: "{character} is at a haunted house",
  210: "{character} gets locked in a store",
  211: "{character} gets lost in a store",
  212: "{character} is are sick",
  213: "{character} eats at a late night drive through",
  214: "{character} takes a late night drive",
  215: "{character} takes a late night walk",
  216: "{character} finds a hidden treasure",
  217: "{character} looks for a hidden treasure",
  218: "{character} keeping a secret",
  219: "{character} baking cookies",
  22: "{character} is at an amusement park",
  220: "{character} has a near death experience",
  221: "{character} gets some really good news",
  222: "{character} gets some really bad news",
  223: "{character} gets bullies",
  224: "{character} gets into a fist fight",
  225: "{character} makes a wish at a wishing well",
  226: "{character} gets bad advice",
  227: "{character} gets caught in the rain",
  228: "{character} gets pranked",
  229: "{character} gets prank called",
  23: "{character} gets lost in the woods",
  230: "{character} toilet papers someone's house",
  231: "Someone toilet papers {character}'s house",
  232: "{character} makes a friendship bracelet for someone",
  233: "{character} doing magic tricks",
  234: "{character} hiding from someone",
  235: "{character} has a bbq",
  236: "{character} has to solve a mystery",
  237: "{character} doing pottery",
  238: "{character} has a bonfire",
  239: "{character} goes horseback riding",
  24: "{character} goes camping",
  240: "{character} playing laser tag",
  241: "{character} goes zip lining",
  242: "{character} is invited to a potluck",
  243: "{character} goes to a government meeting",
  244: "{character} goes to the library",
  245: "{character} fixes a broken toilet",
  246: "{character} unclogs a drain",
  247: "{character} goes to a neighborhood block party",
  248: "{character} cleaning up trash on the side of the road",
  249: "{character} makes paper airplanes",
  25: "{character} goes to the movies",
  250: "{character} reconnects with an old friend",
  251: "{character} reconnects with a family member",
  252: "{character} blowing bubbles",
  253: "{character} saves money",
  254: "{character} plans a vacation",
  255: "{character} goes on vacation",
  256: "{character} gets interviewed on live TV",
  257: "{character} plans a wedding",
  258: "{character} goes to a flea market",
  259: "{character} lies to someone",
  26: "{character} goes on a hike",
  260: "{character} starts a garden",
  261: "{character} gets a surprise",
  262: "{character} gets a terrible gift",
  263: "{character} gives a terrible gift",
  264: "{character} breaks a promise",
  265: "{character} gets caught in a lie",
  266: "{character} gets lost in a store",
  267: "{character} lost in a crowd",
  27: "{character} spends the day fishing",
  28: "{character} is lost in a store",
  29: "{character} bakes a pie",
  3: "{character} participates in a roller derby. ",
  30: "{character} volunteers at a nursing home",
  31: "{character} visit a psychic",
  32: "{character} learns a new skill",
  33: "{character} goes to a Farmer's Market",
  34: "{character} goes thrift shopping",
  35: "{character} watches Halloween movies",
  36: "{character} puts together a jigsaw puzzle",
  37: "{character} cleans out a closet",
  38: "{character} gets a confusing text",
  39: "{character} watching a very sad movie. ",
  4: "{character} goes to a science museum",
  40: "{character} at the beach",
  41: "{character} watching the sunset",
  42: "{character} is at a party and doesn't want to be. ",
  43: "{character} is reading a book but keeps getting distracted. ",
  44: "{character} gets stuck in an elevator",
  45: "{character} is trapped in a closet",
  46: "{character} watches fireworks",
  47: "{character} bought a gift, but lost it on the way home",
  48: "{character} is afraid to ride a roller coaster",
  49: "{character} goes on a road trip",
  5: "Someone has a crush on {character}",
  50: "{character} researches something at the library",
  51: "{character} wants to go trick or treating",
  52: "{character} cooks a holiday meal",
  53: "{character} carves a pumpkin together",
  54: "{character} films a documentary",
  55: "{character} loses a bet",
  56: "{character} plays ping-pong against",
  57: "{character} gets caught in a storm",
  58: "{character} gets stranded at a rest stop",
  59: "{character} is about to do something stupid",
  6: "{character} starts the kitchen on fire",
  60: "{character} gets caught up in the middle of a bank robbery",
  61: "{character} trains in combat",
  62: "{character} makes the ultimate playlist",
  63: "{character} gets a piercing",
  64: "{character} gets a matching tattoos",
  65: "{character} paints a room",
  66: "{character} goes to a child's birthday",
  67: "{character} helps someone move",
  68: "{character} tries to set up a new TV but",
  69: "{character} visits a pumpkin patch",
  7: "{character} mowing the lawn",
  70: "{character} cleans a room",
  71: "{character} takes a day trip to a small town",
  72: "{character} goes to a costume party",
  73: "{character} at a company holiday party",
  74: "{character} gets arrested",
  75: "{character} goes to a professional wrestling show",
  76: "{character} doing arts and crafts",
  77: "{character} puts on a puppet show",
  78: "{character} builds a blanket fort",
  79: "{character} plays hopscotch",
  8: "{character} doing sit ups",
  80: "{character} goes to a farm",
  81: "{character} is shopping",
  82: "{character} on a boat",
  83: "{character} at the local pool",
  84: "{character} doing yoga",
  85: "{character} handing out candy to trick or treaters",
  86: "{character} builds a bird house",
  87: "{character} goes on a jog around the neighborhood",
  88: "{character} needs help finishing a project",
  89: "{character} watching the clouds",
  9: "{character} taking a bubble bath",
  90: "{character} spots an ice cream truck",
  91: "{character} tracks down a food truck",
  92: "{character} jump roping",
  93: "{character} goes to karate class",
  94: "{character} goes to a cooking class",
  95: "{character} has a movie night",
  96: "{character} makes breakfast",
  97: "{character} watches the stars",
  98: "{character} has a picnic",
  99: "{character} feeding ducks",
};

/**
 * list of pop culture fictional characters
 */
export const characters: { [key: string]: string } = {
  0: "Superman",
  1: "Mickey Mouse",
  10: "Rocky Balboa",
  100: "Sonic the Hedgehog",
  11: "Vito Corleone",
  12: "Han Solo",
  13: "Homer Simpson",
  14: "Lucy Ricardo",
  15: "Archie Bunker",
  16: "King Kong",
  17: "Spiderman",
  18: "Barbie",
  19: "Spock",
  2: "James Bond",
  20: "Godzilla",
  21: "The Joker",
  22: "Scarlett O’Hara",
  23: "Winnie-the-Pooh",
  24: "Popeye",
  25: "Tarzan",
  26: "Forrest Gump",
  27: "Hannibal Lector",
  28: "Big Bird",
  29: "Holden Caulfield",
  3: "Bugs Bunny",
  30: "Tony Montana",
  31: "Tony Soprano",
  32: "The Terminator",
  33: "Jon Snow",
  34: "Norman Bates",
  35: "Charles Foster Kane",
  36: "Marty McFly",
  37: "Rick Blaine",
  38: "Man With No Name",
  39: "Charlie Brown",
  4: "Batman",
  40: "E.T.",
  41: "Arthur Fonzarelli",
  42: "Phillip Marlowe",
  43: "Jay Gatsby",
  44: "Lassie",
  45: "Fred Flintstone",
  46: "Rooster Cogburn",
  47: "9 film adaptation",
  48: "Atticus Finch",
  49: "Kermit the Frog",
  5: "Dorothy Gale",
  50: "George Bailey",
  51: "Yoda",
  52: "Zorro",
  53: "Moe, Larry, and Curly",
  54: "Mary Poppins",
  55: "Mario",
  56: "Harry Potter",
  57: "Holly Golightly",
  58: "The Dude",
  59: "Gandalf",
  6: "Darth Vader",
  60: "The Grinch",
  61: "Willy Wonka",
  62: "The Hulk",
  63: "Scooby-Doo",
  64: "Sam Malone",
  65: "George Costanza",
  66: "Jules Winfield",
  67: "John McClane",
  68: "Ellen Ripley",
  69: "Ralph Kramden",
  7: "The Tramp",
  70: "Edward Scissorhands",
  71: "Eric Cartman",
  72: "Walter White",
  73: "Cosmo Kramer",
  74: "Pikachu",
  75: "Michael Scott",
  76: "Freddy Krueger",
  77: "Captain America",
  78: "Goku",
  79: "Bambi",
  8: "Peter Pan",
  80: "Ronald McDonald",
  81: "Waldo/Wally",
  82: "Buffy Summers",
  83: "Frasier Crane",
  84: "Omar Little",
  85: "Wolverine",
  86: "Ron Burgundy",
  87: "Jason Voorhees",
  88: "Betty Boop",
  89: "Bilbo Baggins",
  9: "Indiana Jones",
  90: "Tom Joad",
  91: "Tony Stark",
  92: "Katniss Everdeen",
  93: "Porky Pig",
  94: "Travis Bickle",
  95: "Hawkeye Pierce",
  96: "Don Draper",
  97: "Cliff Huxtable",
  98: "Shrek",
  99: "Optimus Prime",
};
